site_name: My Docs
theme: 
  # name: 'windmill'
  # name: 'rtd-dropdown'
  # name: 'gitbook'
  # name: 'material'
  # name: 'bootstrap4'
  name: 'mkdocs'
  # name: 'ivory'
plugins: ['search']
# nav:
    # - Home: index.md
    # - About: about.md
