
@startuml
[*] --> NORMAL: VIM默认模式
NORMAL -down-> INSERT: i 
INSERT -up-> NORMAL: ESC

NORMAL -right-> COMMAND: ":"
COMMAND -left-> NORMAL: "ESC"

NORMAL -down-> VISUAL: v
VISUAL -up-> NORMAL: ESC

VISUAL -left-> INSERT: i

NORMAL: 浏览
NORMAL: 移动 
NORMAL: 复制 
NORMAL: 粘贴
NORMAL: 删除

VISUAL: 字符选择
VISUAL: 行选择
VISUAL: 块选择

INSERT: 编辑文字

COMMAND: 执行额外的命令
@enduml
